AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  OverlayBackend:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: OverlayBackend
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NodeDependencies
      Description: Node dependencies
      ContentUri: ./dependencies
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs16.x

  ConnectionHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/connectionHandler/
      Handler: connection-handler.connectionHandler
      Timeout: 30
      Layers:
        - !Ref DependenciesLayer
      Runtime: nodejs16.x
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      # CodeUri: ./
      Policies:
        - AWSLambda_FullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  OverlayIdCheckerHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/overlayIdCheckerHandler/
      Handler: overlay-id-checker-handler.overlayIdCheckerHandler
      Timeout: 30
      Runtime: nodejs16.x
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          # Make table names accessible as environment variable from function code during execution
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          OVERLAY_TABLE: !Ref OverlayTable
      # CodeUri: ./
      Policies:
        - AWSLambda_FullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OverlayTable

  OverlayHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/overlayHandler/
      Handler: overlay-handler.overlayHandler
      Timeout: 30
      Runtime: nodejs16.x
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          # Make table names and api key accessible as environment variable from function code during execution
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          OVERLAY_TABLE: !Ref OverlayTable
          WEBSOCKET_API_KEY: "Hpoo7KX6aT85bHmzYgif!Y3E7a7rHkiXgmyaJStb"
      # CodeUri: ./
      Policies:
        - AWSLambda_FullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OverlayTable

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "$connect"
      OperationName: ConnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ConnectionHandlerLambdaIntegration

  ConnectionHandlerLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OverlayBackend
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectionHandlerFunction.Arn}/invocations

  OverlayIdCheckerHandlerLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OverlayBackend
      Description: CheckOverlayCookieId Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OverlayIdCheckerHandlerFunction.Arn}/invocations

  OverlayHandlerLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OverlayBackend
      Description: OverlayHandler Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OverlayHandlerFunction.Arn}/invocations

  CheckOverlayCookieIdRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "checkOverlayCookieId"
      OperationName: CheckOverlayCookieIdRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayIdCheckerHandlerLambdaIntegration

  GetOverlaysRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "getOverlays"
      OperationName: GetOverlaysRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayHandlerLambdaIntegration

  AddOverlayRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "addOverlay"
      OperationName: AddOverlayRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayHandlerLambdaIntegration

  GetOverlayContentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "getOverlayContent"
      OperationName: GetOverlayContentRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayHandlerLambdaIntegration

  TriggerOverlayOnUsersRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "triggerOverlayOnUsers"
      OperationName: TriggerOverlayOnUsersRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayHandlerLambdaIntegration

  SendAnswerToOverlayContentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OverlayBackend
      RouteKey: "sendAnswerToOverlayContent"
      OperationName: SendAnswerToOverlayContentRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OverlayHandlerLambdaIntegration

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: v1
      Description: Version 1 'stage'
      DeploymentId: !Ref Deployment
      ApiId: !Ref OverlayBackend

  ConnectionHandlerFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OverlayBackend
      - ConnectionHandlerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectionHandlerFunction
      Principal: apigateway.amazonaws.com

  OverlayIdCheckerHandlerFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OverlayBackend
      - OverlayIdCheckerHandlerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OverlayIdCheckerHandlerFunction
      Principal: apigateway.amazonaws.com

  OverlayHandlerFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OverlayBackend
      - OverlayHandlerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OverlayHandlerFunction
      Principal: apigateway.amazonaws.com

  DependenciesLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref DependenciesLayer
      Principal: "*"

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ConnectionsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  OverlayTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OverlayTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - CheckOverlayCookieIdRoute
      - GetOverlaysRoute
      - AddOverlayRoute
      - GetOverlayContentRoute
      - TriggerOverlayOnUsersRoute
      - SendAnswerToOverlayContentRoute
      - ConnectRoute
    Properties:
      ApiId: !Ref OverlayBackend
